#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
=============================================================================
  Phase 5 — Always-On DBA Daemon
  Generated by: SRE Automation Node v1.0.0
  Timestamp:    2026-05-24T12:05:20+05:30
=============================================================================
  DESCRIPTION:
    A continuously-running background daemon that monitors a PostgreSQL
    database via pg_stat_statements for slow queries (mean_exec_time > 500ms
    with > 50 calls). When degraded queries are detected, it automatically
    triggers the AI optimization pipeline (Phase 1 → 2 → 3), then sends a
    rich-formatted alert to a Slack or Discord webhook.

  SAFETY GUARANTEES:
    - Read-only DB access (pg_stat_statements SELECT only, no DDL).
    - 24-hour in-memory deduplication cache per queryid to prevent repeated
      optimization of the same query.
    - Full try/except isolation around DB polling, subprocess execution, and
      webhook dispatch — the daemon NEVER crashes on transient failures.

  REQUIREMENTS:
    pip install psycopg2-binary requests

  USAGE:
    python always_on_dba.py
    python always_on_dba.py --db-url postgresql://user:pass@host:5432/dbname
    python always_on_dba.py --webhook-url https://hooks.slack.com/... --interval 60

  ENVIRONMENT VARIABLES (override any CLI flag):
    PG_HOST, PG_PORT, PG_DBNAME, PG_USER, PG_PASSWORD
    WEBHOOK_URL        — Slack or Discord incoming webhook URL
    SLOW_QUERY_MS      — Mean exec time threshold in ms (default: 500)
    MIN_CALLS          — Minimum call count to qualify (default: 50)
    POLL_INTERVAL_SECS — Sleep interval between polls (default: 300)
    PYTHONIOENCODING   — Set to 'utf-8' for correct Unicode on Windows
=============================================================================
"""

import argparse
import hashlib
import json
import os
import subprocess
import sys
import time
from datetime import datetime, timedelta
from pathlib import Path

# ---------------------------------------------------------------------------
# Dependency guard
# ---------------------------------------------------------------------------
# Force UTF-8 stdout/stderr on Windows to prevent charmap encoding crashes
if sys.stdout.encoding and sys.stdout.encoding.lower() != 'utf-8':
    import io
    sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8', errors='replace')
    sys.stderr = io.TextIOWrapper(sys.stderr.buffer, encoding='utf-8', errors='replace')

try:
    import psycopg2
    import psycopg2.extras
except ImportError:
    print("[FATAL] psycopg2 not found. Install it with:  pip install psycopg2-binary")
    sys.exit(1)

try:
    import requests
except ImportError:
    print("[FATAL] requests not found. Install it with:  pip install requests")
    sys.exit(1)

# ---------------------------------------------------------------------------
# Path constants — resolved relative to this script's location
# ---------------------------------------------------------------------------
SCRIPT_DIR          = Path(__file__).parent
ARTIFACTS_DIR       = SCRIPT_DIR / "optimization_artifacts"
PHASE1_QUERY_FILE   = ARTIFACTS_DIR / "slow_query_input.json"   # Written by daemon; read by run_phase_1.py
PRISMA_MD_FILE      = ARTIFACTS_DIR / "PRISMA_INSTRUCTIONS.md"

PHASE1_SCRIPT = SCRIPT_DIR / "optimization_artifacts" / "run_phase_1.py"
PHASE2_SCRIPT = SCRIPT_DIR / "optimization_artifacts" / "run_phase_2.py"
PHASE3_SCRIPT = SCRIPT_DIR / "optimization_artifacts" / "run_phase_3.py"

# ---------------------------------------------------------------------------
# Configuration defaults — all overridable via env vars or CLI
# ---------------------------------------------------------------------------
DEFAULT_DB_CONFIG = {
    "host":     os.getenv("PG_HOST",     "localhost"),
    "port":     int(os.getenv("PG_PORT", "5432")),
    "dbname":   os.getenv("PG_DBNAME",   "postgres"),
    "user":     os.getenv("PG_USER",     "postgres"),
    "password": os.getenv("PG_PASSWORD", ""),
    "connect_timeout": 10,
    "application_name": "always_on_dba_daemon",
}
DEFAULT_WEBHOOK_URL    = os.getenv("WEBHOOK_URL",        "")
DEFAULT_SLOW_QUERY_MS  = int(os.getenv("SLOW_QUERY_MS",  "500"))
DEFAULT_MIN_CALLS      = int(os.getenv("MIN_CALLS",      "50"))
DEFAULT_POLL_INTERVAL  = int(os.getenv("POLL_INTERVAL_SECS", "300"))

# How long (hours) to cache a queryid before allowing re-optimization
CACHE_TTL_HOURS = 24

# ---------------------------------------------------------------------------
# In-memory deduplication cache: { queryid_hash: datetime_last_seen }
# ---------------------------------------------------------------------------
_optimized_cache: dict[str, datetime] = {}


# ---------------------------------------------------------------------------
# Logging helpers
# ---------------------------------------------------------------------------
def _ts() -> str:
    return datetime.now().strftime("%Y-%m-%d %H:%M:%S")

def log_info(msg: str) -> None:
    print(f"[{_ts()}] [INFO]  {msg}", flush=True)

def log_warn(msg: str) -> None:
    print(f"[{_ts()}] [WARN]  {msg}", flush=True)

def log_error(msg: str) -> None:
    print(f"[{_ts()}] [ERROR] {msg}", file=sys.stderr, flush=True)

def log_banner(title: str) -> None:
    bar = "=" * 72
    print(f"\n{bar}\n  {title}\n{bar}\n", flush=True)


# ---------------------------------------------------------------------------
# Deduplication cache helpers
# ---------------------------------------------------------------------------
def _make_cache_key(queryid: int | None, query_text: str) -> str:
    """Create a stable hash key for a query, using queryid if available."""
    raw = str(queryid) if queryid else query_text[:512]
    return hashlib.sha256(raw.encode("utf-8")).hexdigest()


def _is_cached(cache_key: str) -> bool:
    """Return True if this query was optimized within the TTL window."""
    if cache_key not in _optimized_cache:
        return False
    age = datetime.now() - _optimized_cache[cache_key]
    if age > timedelta(hours=CACHE_TTL_HOURS):
        del _optimized_cache[cache_key]
        return False
    return True


def _mark_cached(cache_key: str) -> None:
    """Record that we've dispatched this query to the optimizer."""
    _optimized_cache[cache_key] = datetime.now()


# ---------------------------------------------------------------------------
# PostgreSQL telemetry ingestion
# ---------------------------------------------------------------------------
def fetch_slow_queries(
    db_config: dict,
    min_mean_ms: float,
    min_calls: int,
) -> list[dict]:
    """
    Query pg_stat_statements for the top 5 slowest queries that exceed
    both mean_exec_time and calls thresholds. Returns a list of row dicts.
    Requires only SELECT on pg_stat_statements (read-only access).
    """
    # pg_stat_statements column naming differs by PG version
    # PG ≥ 13: mean_exec_time; PG < 13: mean_time — handle both
    sql = """
        SELECT
            queryid,
            query,
            calls,
            mean_exec_time,
            total_exec_time,
            rows,
            stddev_exec_time,
            shared_blks_read,
            shared_blks_hit
        FROM pg_stat_statements
        WHERE
            mean_exec_time > %(min_mean_ms)s
            AND calls       > %(min_calls)s
        ORDER BY mean_exec_time DESC
        LIMIT 5;
    """

    conn = None
    try:
        conn = psycopg2.connect(**db_config)
        conn.set_session(readonly=True, autocommit=True)
        with conn.cursor(cursor_factory=psycopg2.extras.RealDictCursor) as cur:
            cur.execute(sql, {"min_mean_ms": min_mean_ms, "min_calls": min_calls})
            rows = cur.fetchall()
            return [dict(r) for r in rows]
    except psycopg2.errors.UndefinedTable:
        log_warn("pg_stat_statements view not found. Enable it with: CREATE EXTENSION IF NOT EXISTS pg_stat_statements;")
        return []
    except psycopg2.OperationalError as exc:
        log_error(f"Database connection failed: {exc}")
        return []
    except psycopg2.Error as exc:
        log_error(f"PostgreSQL query error: {exc}")
        return []
    finally:
        if conn:
            try:
                conn.close()
            except psycopg2.Error:
                pass


# ---------------------------------------------------------------------------
# AI pipeline trigger
# ---------------------------------------------------------------------------
def run_ai_pipeline(slow_query: dict, db_config: dict) -> bool:
    """
    Write the slow query to a well-known file so run_phase_1.py can pick
    it up, then execute the pipeline stages sequentially via subprocess.run().
    Returns True if all stages succeed, False otherwise.
    """
    # Write query to the handoff file read by run_phase_1.py
    try:
        ARTIFACTS_DIR.mkdir(parents=True, exist_ok=True)
        PHASE1_QUERY_FILE.write_text(json.dumps(slow_query, indent=2), encoding="utf-8")
        log_info(f"Wrote slow query to: {PHASE1_QUERY_FILE.name}")
    except OSError as exc:
        log_error(f"Failed to write query handoff file: {exc}")
        return False

    pipeline_env = {
        **os.environ,
        "PYTHONIOENCODING": "utf-8",
        "PG_HOST":     db_config.get("host", "localhost"),
        "PG_PORT":     str(db_config.get("port", 5432)),
        "PG_DBNAME":   db_config.get("dbname", "postgres"),
        "PG_USER":     db_config.get("user", "postgres"),
        "PG_PASSWORD": db_config.get("password", ""),
    }

    stages = [
        ("Phase 1 — Diagnostician",   [sys.executable, str(PHASE1_SCRIPT)]),
        ("Phase 2 — HypoPG Evaluator",[sys.executable, str(PHASE2_SCRIPT)]),
        ("Phase 3 — ORM Translator",  [sys.executable, str(PHASE3_SCRIPT)]),
    ]

    for stage_name, cmd in stages:
        log_info(f"Triggering {stage_name}...")
        if not Path(cmd[1]).exists():
            log_warn(f"Script not found, skipping: {cmd[1]}")
            continue
        try:
            result = subprocess.run(
                cmd,
                capture_output=True,
                text=True,
                encoding="utf-8",
                timeout=300,   # 5-minute per-stage timeout
                env=pipeline_env,
                cwd=str(SCRIPT_DIR),
            )
            if result.returncode != 0:
                log_error(f"{stage_name} exited with code {result.returncode}:\n{result.stderr}")
                return False
            log_info(f"{stage_name} completed successfully.")
            if result.stdout.strip():
                # Print final summary line only to keep logs clean
                last_line = result.stdout.strip().splitlines()[-1]
                log_info(f"  └─ {last_line}")
        except subprocess.TimeoutExpired:
            log_error(f"{stage_name} timed out after 300 seconds.")
            return False
        except OSError as exc:
            log_error(f"Failed to launch {stage_name}: {exc}")
            return False

    return True


# ---------------------------------------------------------------------------
# Alert notification (Slack / Discord webhook)
# ---------------------------------------------------------------------------
def _build_slack_payload(slow_query_row: dict, report_md: str) -> dict:
    """Format a Slack Block Kit payload."""
    query_preview = slow_query_row["query"][:300].replace("\n", " ")
    mean_ms       = slow_query_row.get("mean_exec_time", 0)
    calls         = slow_query_row.get("calls", 0)
    report_preview = report_md[:1500] if report_md else "_No report generated._"

    return {
        "text": f"⚠️ Always-On DBA Alert — Slow Query Detected & Optimized",
        "blocks": [
            {
                "type": "header",
                "text": {"type": "plain_text", "text": "⚠️ Always-On DBA Alert"}
            },
            {
                "type": "section",
                "fields": [
                    {"type": "mrkdwn", "text": f"*Mean Exec Time:*\n`{mean_ms:.1f} ms`"},
                    {"type": "mrkdwn", "text": f"*Total Calls:*\n`{calls:,}`"},
                ]
            },
            {
                "type": "section",
                "text": {
                    "type": "mrkdwn",
                    "text": f"*Slow Query (truncated):*\n```{query_preview}```"
                }
            },
            {"type": "divider"},
            {
                "type": "section",
                "text": {
                    "type": "mrkdwn",
                    "text": f"*AI Optimization Report:*\n{report_preview}"
                }
            },
            {
                "type": "context",
                "elements": [
                    {"type": "mrkdwn", "text": f"Generated by Always-On DBA Daemon at `{_ts()}`"}
                ]
            }
        ]
    }


def _build_discord_payload(slow_query_row: dict, report_md: str) -> dict:
    """Format a Discord webhook payload with embeds."""
    query_preview  = slow_query_row["query"][:1000].replace("\n", " ")
    mean_ms        = slow_query_row.get("mean_exec_time", 0)
    calls          = slow_query_row.get("calls", 0)
    report_preview = report_md[:2000] if report_md else "_No report generated._"

    return {
        "content": "⚠️ **Always-On DBA Alert — Slow Query Detected & Optimized**",
        "embeds": [
            {
                "title": "Slow Query Report",
                "color": 16711680,  # Red
                "fields": [
                    {"name": "Mean Exec Time",   "value": f"`{mean_ms:.1f} ms`", "inline": True},
                    {"name": "Total Calls",      "value": f"`{calls:,}`",         "inline": True},
                    {"name": "Slow Query",       "value": f"```sql\n{query_preview}\n```", "inline": False},
                    {"name": "AI Optimization Report", "value": report_preview[:1024], "inline": False},
                ],
                "footer": {"text": f"Always-On DBA Daemon · {_ts()}"}
            }
        ]
    }


def send_webhook_alert(webhook_url: str, slow_query_row: dict, report_md: str) -> None:
    """
    POST a formatted alert to a Slack or Discord webhook.
    Automatically detects the platform from the URL structure.
    """
    if not webhook_url:
        log_warn("No WEBHOOK_URL configured — skipping alert notification.")
        return

    is_discord = "discord.com" in webhook_url or "discordapp.com" in webhook_url

    try:
        if is_discord:
            payload = _build_discord_payload(slow_query_row, report_md)
        else:
            payload = _build_slack_payload(slow_query_row, report_md)

        headers = {"Content-Type": "application/json"}
        resp = requests.post(
            webhook_url,
            data=json.dumps(payload),
            headers=headers,
            timeout=15,
        )
        resp.raise_for_status()
        log_info(f"Webhook alert sent successfully (HTTP {resp.status_code}).")
    except requests.exceptions.Timeout:
        log_error("Webhook request timed out after 15 seconds.")
    except requests.exceptions.ConnectionError as exc:
        log_error(f"Webhook connection failed: {exc}")
    except requests.exceptions.HTTPError as exc:
        log_error(f"Webhook returned error: {exc.response.status_code} — {exc.response.text[:200]}")
    except requests.exceptions.RequestException as exc:
        log_error(f"Unexpected webhook error: {exc}")


# ---------------------------------------------------------------------------
# Main daemon loop
# ---------------------------------------------------------------------------
def run_daemon(db_config: dict, webhook_url: str, min_mean_ms: float, min_calls: int, poll_interval: int) -> None:
    """
    The main infinite loop. Polls pg_stat_statements every `poll_interval`
    seconds, triggers the AI pipeline for new slow queries, and dispatches
    webhook alerts with the generated optimization report.
    """
    log_banner("Phase 5 — Always-On DBA Daemon Starting")
    log_info(f"Polling interval      : {poll_interval}s")
    log_info(f"Slow query threshold  : mean_exec_time > {min_mean_ms}ms")
    log_info(f"Min call threshold    : calls > {min_calls}")
    log_info(f"Cache TTL             : {CACHE_TTL_HOURS} hours")
    log_info(f"Webhook configured    : {'YES' if webhook_url else 'NO (set WEBHOOK_URL to enable)'}")
    log_info(f"Artifacts directory   : {ARTIFACTS_DIR}")
    log_info("\nDaemon is now running. Press Ctrl+C to stop.\n")

    cycle = 0

    while True:
        cycle += 1
        log_banner(f"Poll Cycle #{cycle} — {_ts()}")

        # ── 1. Ingest telemetry from pg_stat_statements ───────────────────
        log_info("Querying pg_stat_statements for slow queries...")
        try:
            slow_queries = fetch_slow_queries(db_config, min_mean_ms, min_calls)
        except Exception as exc:
            log_error(f"Unexpected error during telemetry fetch: {exc}")
            slow_queries = []

        if not slow_queries:
            log_info("No slow queries detected above threshold. System healthy. [OK]")
        else:
            log_warn(f"Found {len(slow_queries)} slow query/queries above threshold!")

            for idx, row in enumerate(slow_queries, start=1):
                query_text = row.get("query", "")
                queryid    = row.get("queryid")
                mean_ms    = row.get("mean_exec_time", 0.0)
                calls      = row.get("calls", 0)

                log_warn(
                    f"  [{idx}] queryid={queryid} | mean={mean_ms:.1f}ms | calls={calls:,}"
                )

                # ── 2. Deduplication check ────────────────────────────────
                cache_key = _make_cache_key(queryid, query_text)
                if _is_cached(cache_key):
                    log_info(f"  [{idx}] Already optimized within {CACHE_TTL_HOURS}h cache window — skipping.")
                    continue

                log_info(f"  [{idx}] New slow query detected — triggering AI optimization pipeline...")

                # ── 3. Trigger AI pipeline ────────────────────────────────
                try:
                    rows_scanned_proxy = row.get("shared_blks_read", 0) + row.get("shared_blks_hit", 0)
                    payload = {
                        "raw_query": query_text,
                        "duration_ms": mean_ms,
                        "rows_returned": row.get("rows", 0),
                        "rows_scanned": rows_scanned_proxy,
                        "payload_size_kb": None
                    }
                    success = run_ai_pipeline(payload, db_config)
                except Exception as exc:
                    log_error(f"  [{idx}] Unhandled error in AI pipeline: {exc}")
                    success = False

                if not success:
                    log_error(f"  [{idx}] AI pipeline failed. Skipping alert for this query.")
                    continue

                # Mark in cache AFTER successful pipeline run
                _mark_cached(cache_key)
                log_info(f"  [{idx}] Query added to 24h deduplication cache.")

                # ── 4. Read optimization report ───────────────────────────
                report_md = ""
                try:
                    if PRISMA_MD_FILE.exists() and PRISMA_MD_FILE.stat().st_size > 0:
                        report_md = PRISMA_MD_FILE.read_text(encoding="utf-8").strip()
                        log_info(f"  [{idx}] Read optimization report: {len(report_md)} chars.")
                    else:
                        log_warn(f"  [{idx}] PRISMA_INSTRUCTIONS.md not found or empty after pipeline run.")
                except OSError as exc:
                    log_error(f"  [{idx}] Could not read report file: {exc}")

                # ── 5. Send webhook alert ─────────────────────────────────
                try:
                    send_webhook_alert(webhook_url, row, report_md)
                except Exception as exc:
                    log_error(f"  [{idx}] Unexpected error sending webhook alert: {exc}")

        # ── Sleep before next poll ────────────────────────────────────────
        log_info(f"Next poll in {poll_interval}s. Sleeping...\n")
        try:
            time.sleep(poll_interval)
        except KeyboardInterrupt:
            log_banner("Daemon Interrupted by User")
            log_info("Shutting down cleanly. All virtual indexes cleaned up.")
            sys.exit(0)


# ---------------------------------------------------------------------------
# CLI entry-point
# ---------------------------------------------------------------------------
def main() -> None:
    parser = argparse.ArgumentParser(
        description=(
            "Phase 5 — Always-On DBA Daemon: monitors pg_stat_statements "
            "and triggers AI optimization pipeline on slow queries."
        ),
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument(
        "--db-url", metavar="DSN",
        help="Full PostgreSQL DSN, e.g. postgresql://user:pass@localhost:5432/dbname. "
             "Overrides individual PG_* environment variables."
    )
    parser.add_argument("--host",     default=DEFAULT_DB_CONFIG["host"],   help="PG host (default: localhost)")
    parser.add_argument("--port",     default=DEFAULT_DB_CONFIG["port"],   type=int, help="PG port (default: 5432)")
    parser.add_argument("--dbname",   default=DEFAULT_DB_CONFIG["dbname"], help="Database name (default: postgres)")
    parser.add_argument("--user",     default=DEFAULT_DB_CONFIG["user"],   help="PG user (default: postgres)")
    parser.add_argument("--password", default=DEFAULT_DB_CONFIG["password"], help="PG password")
    parser.add_argument(
        "--webhook-url", default=DEFAULT_WEBHOOK_URL, metavar="URL",
        help="Slack or Discord incoming webhook URL for alerts."
    )
    parser.add_argument(
        "--threshold-ms", default=DEFAULT_SLOW_QUERY_MS, type=float, metavar="MS",
        help=f"Mean exec time threshold in ms (default: {DEFAULT_SLOW_QUERY_MS})"
    )
    parser.add_argument(
        "--min-calls", default=DEFAULT_MIN_CALLS, type=int, metavar="N",
        help=f"Minimum query call count to qualify (default: {DEFAULT_MIN_CALLS})"
    )
    parser.add_argument(
        "--interval", default=DEFAULT_POLL_INTERVAL, type=int, metavar="SECS",
        help=f"Polling interval in seconds (default: {DEFAULT_POLL_INTERVAL})"
    )

    args = parser.parse_args()

    # Build DB config
    if args.db_url:
        db_config = {"dsn": args.db_url, "connect_timeout": 10, "application_name": "always_on_dba_daemon"}
    else:
        db_config = {
            "host":             args.host,
            "port":             args.port,
            "dbname":           args.dbname,
            "user":             args.user,
            "password":         args.password,
            "connect_timeout":  10,
            "application_name": "always_on_dba_daemon",
        }

    try:
        run_daemon(
            db_config    = db_config,
            webhook_url  = args.webhook_url,
            min_mean_ms  = args.threshold_ms,
            min_calls    = args.min_calls,
            poll_interval= args.interval,
        )
    except KeyboardInterrupt:
        log_banner("Daemon Interrupted by User")
        log_info("Shutting down cleanly.")
        sys.exit(0)


if __name__ == "__main__":
    main()
