#!/usr/bin/env python3
"""
=============================================================================
  Phase 2 — HypoPG Index Hypothesis Evaluator
  Generated by: Diagnostician v1.0.0
  Timestamp:    2026-05-24T10:20:15+05:30
=============================================================================
  DESCRIPTION:
    Reads phase_1_output.json, connects to a local PostgreSQL instance,
    virtually creates each hypothetical index via HypoPG, and measures the
    EXPLAIN cost delta vs. the unoptimized baseline — without any real DDL.

  REQUIREMENTS:
    - pip install psycopg2-binary tabulate colorama
    - PostgreSQL with HypoPG extension installed:
        CREATE EXTENSION IF NOT EXISTS hypopg;
    - A running PostgreSQL instance accessible via the DB_CONFIG below.

  SAFETY GUARANTEE:
    - No real indexes are created.
    - All virtual HypoPG indexes are dropped after each test.
    - Script is read-only from the database's perspective (no writes).

  USAGE:
    python run_phase_2.py
    python run_phase_2.py --db-url postgresql://user:pass@host:5432/dbname
=============================================================================
"""

import argparse
import json
import os
import sys
import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

# ---------------------------------------------------------------------------
# Dependency guard — give the user a clear install hint
# ---------------------------------------------------------------------------
try:
    import psycopg2
    import psycopg2.extras
except ImportError:
    print("[FATAL] psycopg2 not found. Install it with:")
    print("          pip install psycopg2-binary")
    sys.exit(1)

try:
    from tabulate import tabulate
except ImportError:
    tabulate = None  # graceful fallback to plain print

try:
    from colorama import Fore, Style, init as colorama_init
    colorama_init(autoreset=True)
    COLOR = True
except ImportError:
    COLOR = False

# ---------------------------------------------------------------------------
# Configuration — edit these or pass --db-url at runtime
# ---------------------------------------------------------------------------
DEFAULT_DB_CONFIG: dict[str, Any] = {
    "host":     os.getenv("PG_HOST",     "localhost"),
    "port":     int(os.getenv("PG_PORT", "5432")),
    "dbname":   os.getenv("PG_DBNAME",   "postgres"),
    "user":     os.getenv("PG_USER",     "postgres"),
    "password": os.getenv("PG_PASSWORD", ""),
    "connect_timeout": 10,
    "application_name": "diagnostician_phase2",
}

PHASE1_JSON_PATH = Path(__file__).parent / "phase_1_output.json"

# ---------------------------------------------------------------------------
# Colour helpers
# ---------------------------------------------------------------------------
def _green(msg: str) -> str:
    return f"{Fore.GREEN}{msg}{Style.RESET_ALL}" if COLOR else msg

def _red(msg: str) -> str:
    return f"{Fore.RED}{msg}{Style.RESET_ALL}" if COLOR else msg

def _yellow(msg: str) -> str:
    return f"{Fore.YELLOW}{msg}{Style.RESET_ALL}" if COLOR else msg

def _cyan(msg: str) -> str:
    return f"{Fore.CYAN}{msg}{Style.RESET_ALL}" if COLOR else msg

def _bold(msg: str) -> str:
    return f"{Style.BRIGHT}{msg}{Style.RESET_ALL}" if COLOR else msg

# ---------------------------------------------------------------------------
# Data model
# ---------------------------------------------------------------------------
@dataclass
class HypothesisResult:
    hypothesis_id: str
    label: str
    hypoid: int | None = None
    baseline_total_cost: float = 0.0
    hypothesis_total_cost: float = 0.0
    baseline_plan_type: str = ""
    hypothesis_plan_type: str = ""
    cost_delta: float = 0.0
    cost_delta_pct: float = 0.0
    wall_time_ms: float = 0.0
    error: str | None = None
    index_used: bool = False
    raw_plan: dict = field(default_factory=dict)

# ---------------------------------------------------------------------------
# Core functions
# ---------------------------------------------------------------------------

def load_phase1(path: Path) -> dict:
    """Load and validate the Phase 1 JSON artifact."""
    if not path.exists():
        raise FileNotFoundError(
            f"phase_1_output.json not found at: {path}\n"
            "Run the Diagnostician Phase 1 step first."
        )
    with path.open("r", encoding="utf-8") as fh:
        data = json.load(fh)
    required_keys = {"raw_query", "diagnosis", "hypotheses"}
    missing = required_keys - set(data.keys())
    if missing:
        raise ValueError(f"phase_1_output.json is missing required keys: {missing}")
    return data


def get_connection(config: dict) -> psycopg2.extensions.connection:
    """Establish and return a PostgreSQL connection."""
    try:
        conn = psycopg2.connect(**config)
        conn.autocommit = False
        return conn
    except psycopg2.OperationalError as exc:
        raise ConnectionError(
            f"Cannot connect to PostgreSQL at "
            f"{config.get('host')}:{config.get('port')} "
            f"(db={config.get('dbname')}, user={config.get('user')}).\n"
            f"Original error: {exc}"
        ) from exc


def ensure_hypopg(cursor: psycopg2.extensions.cursor) -> None:
    """Verify HypoPG extension is available; raise clearly if not."""
    try:
        cursor.execute("SELECT hypopg_reset();")
    except psycopg2.errors.UndefinedFunction:
        raise RuntimeError(
            "HypoPG extension is not installed or not available in this database.\n"
            "Install it with:  CREATE EXTENSION IF NOT EXISTS hypopg;\n"
            "Docs: https://hypopg.readthedocs.io/"
        )


def extract_plan_cost(plan_json: list) -> tuple[float, str]:
    """
    Recursively extract total cost and top-level node type from EXPLAIN JSON.
    Returns (total_cost, node_type).
    """
    try:
        top_node = plan_json[0]["Plan"]
        total_cost = top_node.get("Total Cost", 0.0)
        node_type = top_node.get("Node Type", "Unknown")
        return float(total_cost), node_type
    except (KeyError, IndexError, TypeError):
        return 0.0, "Unknown"


def check_index_used_in_plan(plan_json: list, hypoid: int) -> bool:
    """
    Walk the plan tree and check whether HypoPG's virtual index (by oid)
    was actually referenced by the planner.
    """
    plan_str = json.dumps(plan_json)
    return f"<hypothetical-index:{hypoid}>" in plan_str or f"btree_{hypoid}" in plan_str


def get_baseline_plan(cursor: psycopg2.extensions.cursor, query: str) -> tuple[float, str, list]:
    """Run EXPLAIN on the bare query and return (cost, node_type, raw_plan)."""
    # Disable all hypothetical indexes to get a clean baseline
    cursor.execute("SELECT hypopg_reset();")
    cursor.execute(f"EXPLAIN (FORMAT JSON, ANALYZE FALSE, COSTS TRUE, BUFFERS FALSE) {query}")
    row = cursor.fetchone()
    # RealDictCursor returns a dict; plain cursor returns a tuple
    plan = row["QUERY PLAN"] if isinstance(row, dict) else row[0]
    cost, node_type = extract_plan_cost(plan)
    return cost, node_type, plan


def evaluate_hypothesis(
    cursor: psycopg2.extensions.cursor,
    hypothesis: dict,
    raw_query: str,
    baseline_cost: float,
    baseline_node_type: str,
) -> HypothesisResult:
    """
    Virtually create one index, run EXPLAIN, measure delta, then clean up.
    All within the same transaction (no commits, no real DDL).
    """
    result = HypothesisResult(
        hypothesis_id=hypothesis["id"],
        label=hypothesis["label"],
        baseline_total_cost=baseline_cost,
        baseline_plan_type=baseline_node_type,
    )

    t_start = time.perf_counter()

    try:
        # ── SAVEPOINT: isolate each hypothesis so an error doesn't abort the tx
        cursor.execute("SAVEPOINT hyp_eval;")

        # ── 1. Create the virtual (hypothetical) index ────────────────────
        hypopg_sql = hypothesis["hypopg_call"]
        cursor.execute(hypopg_sql)
        row = cursor.fetchone()

        if row is None:
            result.error = "hypopg_create_index() returned no rows — check HypoPG version."
            cursor.execute("ROLLBACK TO SAVEPOINT hyp_eval;")
            return result

        result.hypoid = row["indexrelid"] if isinstance(row, dict) else row[0]

        # ── 2. Run EXPLAIN with the virtual index present ─────────────────
        cursor.execute(
            f"EXPLAIN (FORMAT JSON, ANALYZE FALSE, COSTS TRUE, BUFFERS FALSE) {raw_query}"
        )
        row = cursor.fetchone()
        hypo_plan = row["QUERY PLAN"] if isinstance(row, dict) else row[0]
        result.raw_plan = hypo_plan

        hypo_cost, hypo_node_type = extract_plan_cost(hypo_plan)
        result.hypothesis_total_cost = hypo_cost
        result.hypothesis_plan_type = hypo_node_type

        # ── 3. Compute delta ──────────────────────────────────────────────
        result.cost_delta = baseline_cost - hypo_cost
        result.cost_delta_pct = (
            (result.cost_delta / baseline_cost) * 100.0 if baseline_cost > 0 else 0.0
        )
        result.index_used = check_index_used_in_plan(hypo_plan, result.hypoid)

        cursor.execute("RELEASE SAVEPOINT hyp_eval;")

    except psycopg2.Error as exc:
        result.error = f"PostgreSQL error: {exc.pgcode} — {exc.pgerror or str(exc)}"
        try:
            cursor.execute("ROLLBACK TO SAVEPOINT hyp_eval;")
        except psycopg2.Error:
            pass

    finally:
        # ── 4. ALWAYS clean up the virtual index ──────────────────────────
        try:
            if result.hypoid is not None:
                cursor.execute(
                    "SELECT hypopg_drop_index(%s);", (result.hypoid,)
                )
            else:
                cursor.execute("SELECT hypopg_reset();")
        except psycopg2.Error:
            # Best-effort cleanup; reset everything as a safety net
            try:
                cursor.execute("SELECT hypopg_reset();")
            except psycopg2.Error:
                pass

    result.wall_time_ms = (time.perf_counter() - t_start) * 1000.0
    return result


def print_banner(title: str) -> None:
    bar = "=" * 72
    print(_bold(_cyan(f"\n{bar}")))
    print(_bold(_cyan(f"  {title}")))
    print(_bold(_cyan(f"{bar}\n")))


def print_results(results: list[HypothesisResult], baseline_cost: float) -> None:
    """Pretty-print a ranked summary table of all hypothesis results."""
    print_banner("Phase 2 — HypoPG Hypothesis Evaluation Results")

    # Sort by cost delta descending (best improvement first)
    sorted_results = sorted(results, key=lambda r: r.cost_delta, reverse=True)

    rows = []
    for rank, r in enumerate(sorted_results, start=1):
        if r.error:
            status = _red("ERROR")
            cost_after = "—"
            delta = "—"
            delta_pct = "—"
            used = "—"
        else:
            improvement = r.cost_delta_pct
            if improvement > 20:
                status = _green(f"#{rank} ✓ WIN")
            elif improvement > 5:
                status = _yellow(f"#{rank} ~ MARGINAL")
            else:
                status = _red(f"#{rank} ✗ NO GAIN")

            cost_after = f"{r.hypothesis_total_cost:,.2f}"
            delta = _green(f"-{r.cost_delta:,.2f}") if r.cost_delta > 0 else _red(f"+{abs(r.cost_delta):,.2f}")
            delta_pct = _green(f"-{improvement:.1f}%") if improvement > 0 else _red(f"+{abs(improvement):.1f}%")
            used = _green("YES") if r.index_used else _yellow("NO (plan not changed)")

        rows.append([
            status,
            f"[{r.hypothesis_id}] {r.label[:45]}{'…' if len(r.label) > 45 else ''}",
            f"{r.baseline_total_cost:,.2f}",
            cost_after,
            delta,
            delta_pct,
            used,
            f"{r.wall_time_ms:.1f}ms",
        ])

    headers = [
        "Status", "Hypothesis", "Baseline Cost",
        "Hypo Cost", "Δ Cost", "Δ%", "Index Used?", "Wall Time"
    ]

    if tabulate:
        print(tabulate(rows, headers=headers, tablefmt="fancy_grid"))
    else:
        # Fallback plain print if tabulate is not installed
        print(" | ".join(headers))
        print("-" * 100)
        for row in rows:
            print(" | ".join(str(c) for c in row))

    # ── Detailed plan for each successful hypothesis ──────────────────────
    print()
    for r in sorted_results:
        if r.error:
            print(_red(f"\n[{r.hypothesis_id}] ERROR: {r.error}"))
            continue
        print(_bold(f"\n[{r.hypothesis_id}] Raw EXPLAIN (FORMAT JSON) under hypothesis:"))
        # Truncate for readability — full plan available via r.raw_plan
        plan_preview = json.dumps(r.raw_plan, indent=2)
        lines = plan_preview.split("\n")
        if len(lines) > 40:
            lines = lines[:40] + [f"  ... [{len(lines) - 40} more lines, see r.raw_plan] ..."]
        print("\n".join(f"  {line}" for line in lines))


def run_phase2(db_config: dict) -> None:
    """Main orchestration function."""

    # ── Load Phase 1 artifacts ────────────────────────────────────────────
    print_banner("Phase 2 — Loading Phase 1 Artifacts")
    phase1 = load_phase1(PHASE1_JSON_PATH)
    raw_query    = phase1["raw_query"]
    hypotheses   = phase1["hypotheses"]
    diagnosis    = phase1["diagnosis"]
    baseline_ref = phase1.get("baseline_explain", {}).get(
        "Execution Time", "N/A (EXPLAIN ANALYZE not run on baseline)"
    )

    print(f"  Loaded {len(hypotheses)} hypotheses from: {PHASE1_JSON_PATH}")
    print(f"  Primary bottleneck: {diagnosis['primary_bottleneck'][:80]}…")
    print(f"  Baseline execution time (from phase 1): {baseline_ref} ms\n")

    # ── Connect ───────────────────────────────────────────────────────────
    print_banner("Connecting to PostgreSQL")
    conn = get_connection(db_config)
    print(f"  Connected to: {db_config['host']}:{db_config['port']} / {db_config['dbname']}")

    results: list[HypothesisResult] = []

    try:
        with conn.cursor(cursor_factory=psycopg2.extras.RealDictCursor) as cur:

            # ── Verify HypoPG ─────────────────────────────────────────────
            ensure_hypopg(cur)
            print("  HypoPG extension: OK\n")

            # ── Get baseline EXPLAIN cost ─────────────────────────────────
            print_banner("Measuring Baseline EXPLAIN Cost")
            baseline_cost, baseline_node, baseline_plan = get_baseline_plan(cur, raw_query)
            print(f"  Baseline total planner cost : {baseline_cost:,.2f}")
            print(f"  Baseline top-level node type: {baseline_node}\n")

            # ── Evaluate each hypothesis sequentially ─────────────────────
            print_banner("Evaluating Hypotheses via HypoPG")
            for hyp in hypotheses:
                print(f"  ► Testing [{hyp['id']}]: {hyp['label']}")
                result = evaluate_hypothesis(cur, hyp, raw_query, baseline_cost, baseline_node)
                results.append(result)

                if result.error:
                    print(f"    {_red('ERROR:')} {result.error}")
                else:
                    delta_str = (
                        _green(f"Cost reduction: {result.cost_delta_pct:.1f}%")
                        if result.cost_delta_pct > 0
                        else _red(f"No improvement ({result.cost_delta_pct:.1f}%)")
                    )
                    print(f"    {delta_str} | Index used by planner: {result.index_used}")

        # Rollback to ensure NO actual changes persist
        conn.rollback()

    except Exception:
        conn.rollback()
        raise

    finally:
        conn.close()
        print("\n  Connection closed. All virtual indexes cleaned up.")

    # ── Print final results table ─────────────────────────────────────────
    print_results(results, baseline_cost)

    # ── Recommendation ────────────────────────────────────────────────────
    winning = [r for r in results if not r.error and r.cost_delta_pct > 0]
    if winning:
        best = max(winning, key=lambda r: r.cost_delta_pct)
        print(_bold(_green(
            f"\n✅  RECOMMENDATION: Start with [{best.hypothesis_id}] — {best.label}\n"
            f"    Estimated planner cost reduction: {best.cost_delta_pct:.1f}%\n"
            f"    Use the index_definition from phase_1_output.json with CONCURRENTLY.\n"
        )))
    else:
        print(_yellow(
            "\n⚠️  No hypothesis produced a measurable planner cost reduction.\n"
            "    Consider query rewriting, partition pruning, or materialized views.\n"
        ))


# ---------------------------------------------------------------------------
# CLI entry-point
# ---------------------------------------------------------------------------
def main() -> None:
    parser = argparse.ArgumentParser(
        description="Phase 2: HypoPG hypothesis evaluator — reads phase_1_output.json "
                    "and measures virtual index impact on query planner cost.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument(
        "--db-url",
        metavar="DSN",
        help=(
            "PostgreSQL connection string, e.g. "
            "postgresql://postgres:password@localhost:5432/mydb. "
            "Overrides individual PG_* environment variables."
        ),
    )
    parser.add_argument("--host",     default=DEFAULT_DB_CONFIG["host"],   help="PG host (default: localhost)")
    parser.add_argument("--port",     default=DEFAULT_DB_CONFIG["port"],   type=int, help="PG port (default: 5432)")
    parser.add_argument("--dbname",   default=DEFAULT_DB_CONFIG["dbname"], help="Database name (default: postgres)")
    parser.add_argument("--user",     default=DEFAULT_DB_CONFIG["user"],   help="PG user (default: postgres)")
    parser.add_argument("--password", default=DEFAULT_DB_CONFIG["password"], help="PG password")

    args = parser.parse_args()

    if args.db_url:
        # psycopg2 can parse DSN strings directly
        db_config = {"dsn": args.db_url, "connect_timeout": 10}
    else:
        db_config = {
            "host":             args.host,
            "port":             args.port,
            "dbname":           args.dbname,
            "user":             args.user,
            "password":         args.password,
            "connect_timeout":  10,
            "application_name": "diagnostician_phase2",
        }

    try:
        run_phase2(db_config)
    except (FileNotFoundError, ValueError) as exc:
        print(_red(f"\n[FATAL — Artifact Error] {exc}"))
        sys.exit(2)
    except ConnectionError as exc:
        print(_red(f"\n[FATAL — Connection Error] {exc}"))
        sys.exit(3)
    except RuntimeError as exc:
        print(_red(f"\n[FATAL — Runtime Error] {exc}"))
        sys.exit(4)
    except KeyboardInterrupt:
        print(_yellow("\n\nInterrupted by user. Exiting cleanly."))
        sys.exit(0)


if __name__ == "__main__":
    main()
