#!/usr/bin/env python3
"""
=============================================================================
  Phase 3 — ORM Translator Node
  Generated by: AI Assistant
=============================================================================
  DESCRIPTION:
    Reads phase_2_output.json to get the winning index migration.
    Determines if the index can be expressed inline in Prisma.
    If yes: patches prisma/schema.prisma with the @@index attribute.
    If no: generates PRISMA_INSTRUCTIONS.md for a raw SQL bypass.
    Finally, outputs phase_3_output.json.
=============================================================================
"""

import json
import os
import re
import sys
from pathlib import Path

ARTIFACTS_DIR = Path(__file__).parent
PHASE2_JSON_PATH = ARTIFACTS_DIR / "phase_2_output.json"
PHASE3_JSON_PATH = ARTIFACTS_DIR / "phase_3_output.json"
PRISMA_SCHEMA_PATH = ARTIFACTS_DIR.parent / "prisma" / "schema.prisma"
PRISMA_INSTRUCTIONS_PATH = ARTIFACTS_DIR / "PRISMA_INSTRUCTIONS.md"

def load_json(path):
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)

def determine_prisma_inline_def(index_def: str) -> str:
    """
    Rudimentary parser for simple B-Tree index definitions to Prisma @@index.
    E.g. CREATE INDEX CONCURRENTLY idx_orders_status_created_at ON orders (status, created_at DESC);
    """
    # Extract the index name
    name_match = re.search(r"INDEX\s+(?:CONCURRENTLY\s+)?([a-zA-Z0-9_]+)\s+ON", index_def, re.IGNORECASE)
    idx_name = name_match.group(1) if name_match else "idx_custom"

    # Extract the columns inside the parentheses
    cols_match = re.search(r"\(([^)]+)\)", index_def)
    if not cols_match:
        return ""
    
    cols_raw = cols_match.group(1).split(",")
    prisma_cols = []
    
    for col_def in cols_raw:
        col_def = col_def.strip()
        parts = col_def.split()
        col_name = parts[0]
        
        # Simple snake_case to camelCase conversion
        parts_camel = col_name.split('_')
        camel_name = parts_camel[0] + ''.join(word.capitalize() for word in parts_camel[1:])
        
        # Check for sort order
        if len(parts) > 1 and parts[1].upper() == "DESC":
            prisma_cols.append(f"{camel_name}(sort: Desc)")
        else:
            prisma_cols.append(camel_name)
            
    cols_str = ", ".join(prisma_cols)
    return f'@@index([{cols_str}], name: "{idx_name}")'

def run_phase3():
    print("=" * 72)
    print("  Phase 3 — ORM Translator Node")
    print("=" * 72 + "\n")
    
    if not PHASE2_JSON_PATH.exists():
        print(f"[FATAL] {PHASE2_JSON_PATH} not found.")
        sys.exit(1)
        
    phase2 = load_json(PHASE2_JSON_PATH)
    winning = phase2.get("winning_hypothesis")
    
    if not winning:
        print("[FATAL] No winning hypothesis found in phase 2.")
        sys.exit(1)
        
    label = winning.get("label", "")
    index_def = winning.get("index_definition", "")
    print(f"► Winning index: {label}")
    
    # Feature detection for raw migration requirement
    requires_raw = "INCLUDE" in index_def.upper() or "WHERE" in index_def.upper()
    
    # Identify model from table name in definition
    match = re.search(r"ON\s+([a-zA-Z0-9_]+)\s*\(", index_def, re.IGNORECASE)
    table_name = match.group(1) if match else "Unknown"
    
    # Simple table to Model name mapping (singularize & capitalize)
    model_name = table_name.capitalize()
    if table_name.endswith('s'):
        model_name = table_name[:-1].capitalize()
        
    print(f"► Target Model identified: {model_name} (from table '{table_name}')")
    
    if not requires_raw:
        print("► Implementation: INLINE (Prisma native @@index supported)")
        inline_def = determine_prisma_inline_def(index_def)
        print(f"  Generated attribute: {inline_def}")
        
        phase3_output = {
            "status": "success",
            "implementation_type": "inline",
            "index_definition": inline_def,
            "model": model_name,
            "requires_raw_migration": False,
            "notes": "Index is supported natively by Prisma's standard @@index syntax."
        }
        
        if PRISMA_SCHEMA_PATH.exists():
            with open(PRISMA_SCHEMA_PATH, "r", encoding="utf-8") as f:
                schema_content = f.read()
                
            # Check if we already patched it
            if inline_def not in schema_content:
                pattern = f"(model {model_name} {{[\\s\\S]*?)(\\n\\s*}})"
                replacement = f"\\1\n  {inline_def}\\2"
                new_schema = re.sub(pattern, replacement, schema_content)
                with open(PRISMA_SCHEMA_PATH, "w", encoding="utf-8") as f:
                    f.write(new_schema)
                print(f"  [SUCCESS] Appended to {model_name} in schema.prisma")
            else:
                print(f"  [INFO] schema.prisma already contains the index for {model_name}.")
        else:
            print(f"  [WARNING] schema.prisma not found at {PRISMA_SCHEMA_PATH}")
            
    else:
        print("► Implementation: RAW SQL (Unsupported Prisma features like INCLUDE/WHERE detected)")
        phase3_output = {
            "status": "success",
            "implementation_type": "raw_sql",
            "index_definition": index_def,
            "model": model_name,
            "requires_raw_migration": True,
            "notes": "Index uses advanced features (INCLUDE/WHERE) not fully supported by standard Prisma @@index."
        }
        
        # Write markdown instructions for raw migration
        with open(PRISMA_INSTRUCTIONS_PATH, "w", encoding="utf-8") as f:
            f.write("# Prisma Raw Migration Instructions\n\n")
            f.write("Your index requires raw SQL because it utilizes advanced features (e.g. `INCLUDE` or partial index `WHERE`).\n\n")
            f.write("### Step 1: Create an empty migration\n")
            f.write("```bash\n")
            f.write("npx prisma migrate dev --create-only --name manual_optimization_index\n")
            f.write("```\n\n")
            f.write("### Step 2: Paste the SQL\n")
            f.write("Open the generated `migration.sql` file in `prisma/migrations/` and paste the following:\n\n")
            f.write("```sql\n")
            f.write(f"{index_def}\n")
            f.write("```\n\n")
            f.write("### Step 3: Apply the migration\n")
            f.write("```bash\n")
            f.write("npx prisma migrate deploy\n")
            f.write("```\n")
            
        print(f"  [SUCCESS] Generated manual instructions at {PRISMA_INSTRUCTIONS_PATH.name}")

    # Write the phase 3 output artifacts
    with open(PHASE3_JSON_PATH, "w", encoding="utf-8") as f:
        json.dump(phase3_output, f, indent=2)
    print(f"► Saved translation artifacts to {PHASE3_JSON_PATH.name}\n")
    print("✅  Phase 3 ORM Translation Pipeline Complete!")

if __name__ == "__main__":
    run_phase3()
